# Generated by Django 3.0.3 on 2021-11-07 11:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('description', models.TextField(blank=True, default='description', null=True)),
                ('slug', models.SlugField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('popular', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('coursename', models.CharField(blank=True, max_length=250, null=True)),
                ('venue', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/slide/')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='content', null=True)),
                ('slug', models.SlugField(editable=False, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='headshots/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=10)),
                ('content', ckeditor.fields.RichTextField(blank=True, default='content', null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('popular', models.BooleanField(blank=True, null=True)),
                ('venue_1', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_2', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_3', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_4', models.CharField(blank=True, max_length=200, null=True)),
                ('date_1', models.DateField(blank=True, null=True)),
                ('date_2', models.DateField(blank=True, null=True)),
                ('date_3', models.DateField(blank=True, null=True)),
                ('date_4', models.DateField(blank=True, null=True)),
                ('date_5', models.DateField(blank=True, null=True)),
                ('date_6', models.DateField(blank=True, null=True)),
                ('date_7', models.DateField(blank=True, null=True)),
                ('date_8', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coursecategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gov.Category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
