# Generated by Django 3.0.2 on 2020-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course_slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_8',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
