# Generated by Django 3.0.2 on 2020-02-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_auto_20200211_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coursecategory',
        ),
        migrations.AddField(
            model_name='post',
            name='coursecategory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gov.Category'),
        ),
    ]
