# Generated by Django 3.0.2 on 2020-02-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0004_auto_20200212_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coursecategory',
            new_name='slug',
        ),
    ]
