# Generated by Django 3.0.2 on 2020-02-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0005_auto_20200212_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coursecategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gov.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
