# Generated by Django 3.0.3 on 2020-02-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0006_auto_20200212_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='coursename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
